# -*- coding: utf-8 -*-
"""ProyectoRNT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJChp4UBhHRfV4K6z52xZdRLqPumB9wX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from google.colab import drive
drive.mount('/content/drive')

ruta = '/content/drive/MyDrive/ProyectoRNT/Registro_Nacional_de_Turismo_-_RNT_20251016.csv'
data = pd.read_csv(ruta)

data

data.info()

col_nulas = data.isnull().sum()
data["RAZON_SOCIAL_ESTABLECIMIENTO"].fillna("DESCONOCIDO",inplace=True)
col_nulas

#convertir numero de empleados, numero de camas, y numero de habitaciones a tipo numerico
data["NUMERO_DE_EMPLEADOS"] = pd.to_numeric(data["NUMERO_DE_EMPLEADOS"], errors="coerce")
data["NUMERO_DE_CAMAS"] = pd.to_numeric(data["NUMERO_DE_CAMAS"], errors="coerce")
data["NUMERO_DE_HABITACIONES"] = pd.to_numeric(data["NUMERO_DE_HABITACIONES"], errors="coerce")
data.info()

data["DEPARTAMENTO"].unique()

df_filtrado_quindio = data[data["DEPARTAMENTO"] == "QUINDIO"]
cols_numericas = ['NUMERO_DE_HABITACIONES', 'NUMERO_DE_CAMAS', 'NUMERO_DE_EMPLEADOS']
descriptive_stats = pd.DataFrame({
    'Media': df_filtrado_quindio[cols_numericas].mean(),
    'Mediana': df_filtrado_quindio[cols_numericas].median(),
    'Desviacion_Estandar': df_filtrado_quindio[cols_numericas].std(),
    'Minimo': df_filtrado_quindio[cols_numericas].min(),
    'Maximo': df_filtrado_quindio[cols_numericas].max()
})
descriptive_stats

#df_media=df_filtrado_quindio[["NUMERO_DE_HABITACIONES","NUMERO_DE_CAMAS","NUMERO_DE_EMPLEADOS"]].mean()
#df_media

# 4. LIMPIEZA DE DATOS
# ============================================================

# Estandarizar nombres de columnas
df_filtrado_quindio.columns = df_filtrado_quindio.columns.str.strip().str.lower().str.replace(" ", "_")

# Reemplazar nulos y limpiar texto
df_filtrado_quindio.fillna("No disponible", inplace=True)

# Eliminar duplicados
df_filtrado_quindio.drop_duplicates(inplace=True)

# Configuración para que los gráficos de seaborn se vean bien
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# 5. ANÁLISIS DESCRIPTIVO
# ============================================================

# Tipos de prestadores más comunes
plt.figure(figsize=(10,5))
df_filtrado_quindio["categoria"].value_counts().head(10).plot(kind="bar", color="teal")
plt.title("Categorías más frecuentes en el RNT - Quindío")
plt.xlabel("Categoría")
plt.ylabel("Número de registros")
plt.show()

# Municipios con más registros
plt.figure(figsize=(10,5))
df_filtrado_quindio["municipio"].value_counts().head(10).plot(kind="barh", color="orange")
plt.title("Municipios con más establecimientos turísticos")
plt.xlabel("Cantidad de registros")
plt.ylabel("Municipio")
plt.show()

# 6. MODELO DE RECOMENDACIÓN SIMPLE
# ============================================================

# Seleccionar columnas relevantes
cols = ["categoria", "municipio", "razon_social"]

# Crear matriz de características codificadas
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df_filtrado_quindio["info"] = df_filtrado_quindio["categoria"].astype(str) + " " + df_filtrado_quindio["municipio"].astype(str)
vectorizer = CountVectorizer()
matriz = vectorizer.fit_transform(df_filtrado_quindio["info"])

# Calcular similitud
similaridad = cosine_similarity(matriz, matriz)

# Función de recomendación
def recomendar_establecimientos(nombre, n=5):
    try:
        idx = df_filtrado_quindio[df_filtrado_quindio["razon_social"].str.contains(nombre, case=False, na=False)].index[0]
        scores = list(enumerate(similaridad[idx]))
        scores = sorted(scores, key=lambda x: x[1], reverse=True)
        indices = [i[0] for i in scores[1:n+1]]
        recomendados = df_filtrado_quindio.iloc[indices][["razon_social", "categoria", "municipio"]]
        return recomendados
    except IndexError:
        return "No se encontró el establecimiento."

!pip install streamlit

#7. INTERFAZ STREAMLIT (EJECUTAR CON: streamlit run ProyectoRNT.py)
# ============================================================
import streamlit as st
def app_streamlit():
    st.title("🌴 Recomendador Turístico - Quindío")
    st.markdown("Sistema de recomendación basado en el Registro Nacional de Turismo (RNT)")

    nombre = st.text_input("Ingrese el nombre o parte del nombre del establecimiento:")
    n = st.slider("Número de recomendaciones", 1, 10, 5)

    if st.button("Recomendar"):
        resultado = recomendar_establecimientos(nombre, n)
        if isinstance(resultado, str):
            st.warning(resultado)
        else:
            st.dataframe(resultado)

    st.markdown("---")
    st.write("*Total de registros analizados:*", len(df_filtrado_quindio))
    st.bar_chart(df_filtrado_quindio["municipio"].value_counts())

# Descomentar la siguiente línea para ejecutar localmente
app_streamlit()

# 8. CONCLUSIONES AUTOMÁTICAS
# ============================================================

print("🏁 Conclusiones:")
print("- Se analizaron", len(df_filtrado_quindio), "registros del RNT correspondientes al departamento del Quindío.")
print("- Los municipios con más registros son:", ", ".join(df_filtrado_quindio['municipio'].value_counts().head(3).index))
print("- El sistema de recomendación usa similitud de texto entre categoría y municipio.")
print("- Puede servir como herramienta inicial para orientar turistas y analizar la oferta del sector.")

